### ISSUE TITLE
Global configuration not taken into account

### ISSUE THREAD

**Issue by cglacet** [harrysolovay/rescripts#114]
When I use a local `.babelrc` configuration everything works as expected, but when I switch to a global configuration file (renaming `babelrc` to `babel.config.json`), I get the following error: 

```bash
compose requires at least one argument
```

If I use both files, it works but the global configuration seems to be ignored.

Just in case, here is my babel configuration:

```json
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ],
    "plugins": [
        [
          "@babel/plugin-proposal-class-properties"
        ]
    ]
}
```

**Comment by harrysolovay** [comment]
Can you please share your Rescripts configuration?
