### ISSUE TITLE
Dev server hangs when trying to add another entry point

### ISSUE THREAD

**Issue by npearson72** [harrysolovay/rescripts#116]
I just built a fresh CRA app, which provided the following dep versions in my `package.json`:

```
...
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.0",
...
```

I added rescipts:
```
...
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.0",
    "@rescripts/cli": "^0.0.14"
...
```

And changed my `start` command to:

```
...
  "scripts": {
    "start": "rescripts start"
...
```

I then added a `.rescriptsrc.js` file to the project's root and it contains the following:

```
module.exports = config => {
  config.entry = {
    ...config.entry,
    background: './src/background.js'
  };

  return config;
};
```

When I run the `yarn start` command, the CLI just gets stuck at `Starting the development server...`

It opens a tab in Chrome with a blank page and continues to load. It's stuck.

Any ideas?

**Comment by harrysolovay** [comment]
Try resolving the full entry path on disk. Aka:

```js
const path = require("path");

module.exports = config => {
  config.entry = {
    ...config.entry,
    background: path.resolve(__dirname, './src/background.js')
  };

  return config;
};
```

**Comment by npearson72** [comment]
Doesn't work.

You're welcome to see for yourself: https://github.com/npearson72/test

**Comment by harrysolovay** [comment]
I'm not sure if editing the webpack config is the right solution. Just searched and found [this resource](https://blog.logrocket.com/multiple-entry-points-in-create-react-app-without-ejecting/). Sorry that I can't provide more assistance for your use case.

**Comment by npearson72** [comment]
I've moved on the https://razzlejs.org

Mucking with CRA isn't worth it to me.
