### ISSUE TITLE
Adding ".babelrc" breaks typescript support in react

### ISSUE THREAD

**Issue by Sheharyar566** [harrysolovay/rescripts#123]
Hi there,

I'm having this issue with react which requires me to add '@babel/preset-react' to my babel config. So, somehow, I stumbled onto this awesome package which let me do just that.

(Before adding the '@babel/preset-react')
![image](https://user-images.githubusercontent.com/29799626/104087061-d9e5b900-527e-11eb-89aa-5556b9b48714.png)

But after I added that, I started facing another issue which seems like breaking the typescript support...
![image](https://user-images.githubusercontent.com/29799626/104087090-15808300-527f-11eb-810a-c6b63a93f0f4.png)

So I thought, may be I'm missing "react-app" in the presets section as mentioned in this issue: #78  and so I included the "react-app" in the presets, but the original error is still there.
![image](https://user-images.githubusercontent.com/29799626/104087152-7b6d0a80-527f-11eb-94d1-a6440b1ae421.png)

Here is my config... (using CRA non-ejected)...
```
package.json
```
```
{
  "name": "chat",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.8",
    "@testing-library/react": "^11.2.2",
    "@testing-library/user-event": "^12.6.0",
    "@types/jest": "^26.0.20",
    "@types/node": "^12.19.12",
    "@types/react": "^16.14.2",
    "@types/react-dom": "^16.9.10",
    "@types/react-native": "^0.63.44",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-native": "^0.63.4",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-web": "^0.14.10",
    "react-scripts": "4.0.1",
    "realm": "^10.1.2",
    "stanza": "^12.15.0",
    "typescript": "^4.1.3",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "rescripts start",
    "build": "rescripts build",
    "test": "rescripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-syntax-jsx": "^7.12.1",
    "@babel/plugin-transform-typescript": "^7.12.1",
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-react": "^7.12.10",
    "@babel/preset-typescript": "^7.12.7",
    "@rescripts/cli": "0.0.15",
    "@rescripts/rescript-use-babel-config": "0.0.10"
  },
  "rescripts": [
    ["use-babel-config", ".babelrc.js"]
  ]
}
```

and here's my babelrc.js
```
.babelrc.js
```
```
module.exports = {
    "presets": ["@babel/preset-react", "react-app"]
}
```

**Comment by harrysolovay** [comment]
The babel config for TypeScript projects is subtly different I believe. [Here](https://github.com/facebook/create-react-app/tree/master/packages/babel-preset-react-app#usage-with-typescript) are the docs.

Seems you'll need to pass arguments to the preset `"typescript": true`
