### ISSUE TITLE
g.call is not a function

### ISSUE THREAD

**Issue by tranhl** [harrysolovay/rescripts#16]
Getting this error when starting the dev server.

My config:
```js
const configOverrides = {
  webpack: [
    ['use-eslint-config', '.eslintrc'],
    config => injectEmotionBabelPlugin(config),
  ],
  devServer: [
    config => addSettingsFolderToContentBase(config),
  ],
}
```

Excluding the `['use-eslint-config', '.eslintrc']` rescript solves the problem.

**Comment by tranhl** [comment]
Thanks, that solved the problem I was having.
Judging from your example of correct API usage, am I correct in thinking that something like this would also work?
```js
module.exports = [
  ['use-eslint-config', '.eslintrc'],
  {
    webpack: [
      injectEmotionBabelPlugin,
      // As many rescript functions as you need
    ],
    devServer: [
      addSettingsFolderToContentBase,
      // As many rescript functions as you need
    ],
  },
]
```

**Comment by harrysolovay** [comment]
That wouldn't work. Although I kind of like that DX idea 👍will consider it in the next release.

Glad to hear your problem is solved :)

**Comment by harrysolovay** [comment]
Hi @eryon –– that's because the `jest` prop's value needs to be a function, which takes in the last config and returns the updated config. Try this:

```js
module.exports = [
  ['use-babel-config', '.babelrc'],
  {
    jest: config => ({
      ...config,
      collectCoverageFrom: [
        'src/**/*.{js,jsx,mjs}'
      ],
      snapshotSerializers: [
        'enzyme-to-json/serializer'
      ],
      testPathIgnorePatterns: [
        '/node_modules/',
        '<rootDir>/src/config/'
      ],
    }),
  },
]
```

**Comment by eryon** [comment]
@harrysolovay thanks for that, it solved this error. Do you know if you are passing the babel override to react-scripts Jest transformation? I am getting this error now, despite having the babel configured as above:
```
 FAIL  src/App.test.js
  ● Test suite failed to run

    SyntaxError: <path>\src\App.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (31:1):

      29 | };
      30 | 
    > 31 | @inject('theme', 'sessionService')
         | ^
      32 | @observer
      33 | class App extends Component<AppProps, any> {
```
