### ISSUE TITLE
Overriding ts-loader

### ISSUE THREAD

**Issue by Dorious** [harrysolovay/rescripts#18]
I want to add a plugin to ts-loader like ts-import-plugin? 
https://github.com/Brooooooklyn/ts-import-plugin

But all example I can find are for webpack plugins.

**Comment by harrysolovay** [comment]
Hi @Dorious –– this is a little tricky seeing as `react-scripts` doesn't use `ts-loader`; it processes TypeScript via Babel with the help of [@babel/preset-typescript](https://babeljs.io/docs/en/babel-preset-typescript). For your use case, this is actually good news––it appears the package you want to install is a TypeScript-specific layer on top of a Babel plugin ([babel-plugin-import](https://github.com/ant-design/babel-plugin-import)). By using `@rescripts/rescript-use-babel-config`, you can make use of babel-plugin-import directly. The default CRA TS config has ES module interoperability set to true... as long as you keep this setting as is, Babel will do the trick for you. No need for `ts-import-plugin`. Here's what you'll want to do:

`npm i -D babel-plugin-import`

`.rescriptsrc.js`

```js
module.exports = [
  ['use-babel-config', {
    plugins: [
      ['import', {
        "libraryName": "antd",
        "style": true,
      }]
    ]
  }]
]
```

If you really want to override the ES+TS loader, you can do so with [the Rescripts SDK](https://github.com/harrysolovay/rescripts#rescript-sdk)

**Comment by harrysolovay** [comment]
^ this example is for importing antd components –– yours might be different

**Comment by Dorious** [comment]
Ok added this, but it doesn't seem to load any css ;(
Also how to add less-loader?

**Comment by Dorious** [comment]
Ok figured out that there can't be `"rescripts"` key inside `package.json`, will figure out how to make less-loader work. Thanks a lot!

**Comment by harrysolovay** [comment]
You actually can use a `rescripts` key in your `package.json`... unless you're trying to use JS in your Rescripts config. Please let me know if you run into any troubles with using less-loader.

**Comment by Dorious** [comment]
Success! Just for the record how I've made it in `.rescriptsrc.js`:
```javascript
module.exports = [
  [
    'use-babel-config', {
      presets: ['react-app'],
      plugins: [
        ['import', {
          libraryName: "antd",
          style: true,
        }]
      ]
    }
  ],
  config => {
    const newConfig = config;
    
    let rule = newConfig.module.rules.find(rule => rule.oneOf);

    rule.oneOf.unshift(
      {
        test: /\.less$/,
        use: [{
          loader: 'style-loader',
        },
        {
          loader: 'css-loader',
        },
          {
          loader: 'less-loader', 
          options: {
            javscriptEnabled: true,
            modifyVars: { "@primary-color": "#1DA57A" }
          }
        }]
      }
    );

    return newConfig;
  }
]
```
