### ISSUE TITLE
--config parameter for CLI

### ISSUE THREAD

**Issue by matej-prokop** [harrysolovay/rescripts#21]
Would it be possible to introduce option `--conf` to specify path to file with rescript config? Example usage: `rescripts start --conf /path/to/config/rescript-config.js`

## My motivation:
I have multiple web projects using rescripts. In all projects, I have the same local configuration within `.rescriptsrc.js` file. Whenever I make change to one I update it in all repositories. It is similar for eslint, prettier configuration, etc. Therefore, I decided to extract it into `web-scripts` library which is collection of my custom scripts and common configuration on one place (something similar to https://github.com/kentcdodds/kcd-scripts) 

Within my web-projects I "proxy" scripts in `package.json` to web-scripts, example:
```
scripts: {
  "start: "web-scripts start",
  "lint": "web-scripts lint",
  "format: "web-scripts format",
  ... 
}
```
Then `web-scripts` has the share configuration, so `web-scripts` executes

`npx eslint --config ./web-scripts/configuration/eslint-cfg.js`

for lint target. I would love to use similar approach for rescript :)

**Comment by harrysolovay** [comment]
Hi @matej-prokop thanks for the feature request. Here ya go :) https://github.com/harrysolovay/rescripts/commit/c578583d76e07a6745f4b1d51b9daf6b5fa8c106

**Comment by matej-prokop** [comment]
It isn't working for me because library doesn't expect absolute path. It tries to read it only "from root". I proposed this update within https://github.com/harrysolovay/rescripts/pull/22. Let's see if you will like it :) It also show more user friendly error if config wasn't find.

**Comment by harrysolovay** [comment]
Gotcha –– fixed in https://github.com/harrysolovay/rescripts/commit/9d094f0bd25f30ee3cb38152472dfde189ba7730 👍
