### ISSUE TITLE
please help...

### ISSUE THREAD

**Issue by duhongjun** [harrysolovay/rescripts#23]
i have trouble when i override config.. here is my code 
```
module.exports = [
  [
    'use-babel-config',
    {
      presets: ['react-app'],
      plugins: [
        [
          'import',
          {
            libraryName: 'antd',
            libraryDirectory: 'es',
            style: true
          }
        ],
        'transform-decorators-legacy'
      ]
    }
  ],
  config => {
    console.log(config)
    RegExp.prototype.toJSON = RegExp.prototype.toString
    Function.prototype.toJSON = Function.prototype.toString
    fs.writeFileSync('webpack-config.json', JSON.stringify(newConfig, null, 2))
    return config
  }
]
```

i found that there is no log in terminal and not create the 'webpack-config.json' file, also i got no error...  
it seems that the code was not ran ...
could you please help me to firgue out what should i do ...

 "@rescripts/cli": "0.0.10",
 "@rescripts/rescript-env": "0.0.5",
 "react-scripts": "2.1.3",
 .rescriptsrc.js at root dir

**Comment by hosmelq** [comment]
You have to remove "rescripts" from your package.json.

**Comment by harrysolovay** [comment]
@duhongjun `newConfig` is undefined. Change it to config and it'll work as you expect it to.

@hosmelq , where do you see the `package.json`?

**Comment by duhongjun** [comment]
wow .... when i remove the code below , it works...   why ?

![image](https://user-images.githubusercontent.com/18900868/51720650-7cec9a80-2089-11e9-9f0c-449be3fbf062.png)

**Comment by harrysolovay** [comment]
@duhongjun that's because you're specifying the "root rescript" in your `package.json`, which overrides the `.rescriptsrc.js` file in your root directory. To fix this, add the following in the `package.json`'s "rescripts" field:

```diff
"rescripts": [
  "env",
+ ".rescriptsrc.js"
]
```

**Comment by duhongjun** [comment]
it works ..  thanks !

**Comment by duhongjun** [comment]
@harrysolovay @hosmelq   I got error ...    it worked well before, but suddenly it didn't work
![image](https://user-images.githubusercontent.com/18900868/51818562-6acd5f00-230a-11e9-99d7-d7cc27c2df0c.png)

"@rescripts/cli": "0.0.10",
"@rescripts/rescript-env": "0.0.5"

```
// package.json
 "rescripts": [
    "env",
    ".rescriptsrc.js"
  ]


// .rescriptsrc.js
module.exports = [
  [
    'use-babel-config',
    {
      presets: ['react-app'],
      plugins: [
        [
          'import',
          {
            libraryName: 'antd',
            libraryDirectory: 'es',
            style: true
          }
        ],
        ['@babel/plugin-proposal-decorators', { legacy: true }]
      ]
    }
  ],
]
```

i dont know where is invalid,  though i delete all config just keep the code below, i still got the same error..
```
module.exports = [
  [
    'use-babel-config',
    {
      presets: ['react-app'],
      plugins: []
    }
  ]
]
```

**Comment by harrysolovay** [comment]
Hi @duhongjun –– try this: in your `package.json`, get rid of 'env' (it's not additive in your case).

If it's still broken, I'll need to see your project in order to help debug. Is there a link to the repo that you could share with me?

**Comment by duhongjun** [comment]
delete `env` was not worked...
so i tried: 

1. remove package-lock.json
2.  `npm cache clean -f  && rm -rf node_modules && npm i `

and then it worked...
emmmm....
