### ISSUE TITLE
Error in path when loading stylelint config

### ISSUE THREAD

**Issue by endikaserra** [harrysolovay/rescripts#25]
Hi! I'm currently trying to load my .stylelintrc.json config but when I add it to .rescriptsrc.js it looks my .stylelintrc.json file 2 paths above the project folder

```
// .rescriptsrc.js
module.exports = [
  ['use-babel-config', '.babelrc'],
  ['use-stylelint-config', '.stylelintrc.json']
]
```

```
// .stylelint.json
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-styled-components"
  ],
  "rules": {
      "no-descending-specificity": null
    }
}
```

Thanks in advance!

**Comment by harrysolovay** [comment]
Hi @euskonadox –– I'm pretty sure it's a problem relating to [stylelint-custom-processor-loader](https://github.com/emilgoldsmith/stylelint-custom-processor-loader). One solution is to leave the path argument undefined and rename your `.stylelintrc.json` to `.stylelintrc`. That should do it. I need to remove the path option from this package. Hope this is helpful! Please let me know if it doesn't work.

**Comment by euskonadox** [comment]
Hi again! 

I've tried your solution but it doesn't seems to work, I've changed ```.stylelintrc.json``` to ```.stylelintrc``` and when I run the following code:
```
module.exports = [['use-babel-config', '.babelrc'], ['use-stylelint-config']]
```

It gives me the following:
```The "path" argument must be of type string. Received type undefined```

I've tried leaving an empty string but also fails:
```Could not load StyleLint configuration '' relative to your project root nor node_modules'
```

**Comment by harrysolovay** [comment]
@euskonadox what if you remove the the "[" and "]" around the `'use-stylelint-config'`? If that fails, please try specifying '.stylelintrc' as the argument.

**Comment by euskonadox** [comment]
@harrysolovay with the following:
```module.exports = [['use-babel-config', '.babelrc'], 'use-stylelint-config']```
shows:
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration should be an object.

and with 
```
module.exports = [
  ['use-babel-config', '.babelrc'],
  'use-stylelint-config',
  '.stylelintrc'
]
```
it shows: 

It seems that your Rescripts configuration is invalid. Please refer to the docs or post an issue if you believe this to be an internal bug. Thank you!

**Comment by harrysolovay** [comment]
Uh oh. I gotta set aside some time and get to this. I don't have the bandwidth until the weekend. Sorry about that! Will ping you as soon as I've found / published the fix.

**Comment by euskonadox** [comment]
No problem! I'll use without stylelint until then

Thanks for your effort =)

**Comment by harrysolovay** [comment]
@euskonadox the dependency `stylelint-custom-processor-loader` is broken (adds a '../' in between the filename and its path). I'm gonna swap it out with [stylelint-processor-styled-components](https://github.com/styled-components/stylelint-processor-styled-components), which is more supported and should do the trick.

I still don't have the time sadly. This is absolutely on my todo list. But it might be a short while (2 weeks).

If you're in need of this feature sooner, please fork Rescripts, swap out that dependency, edit the `use-stylelint-config` rescript, and submit a PR. Your help would be greatly appreciated. Otherwise, I'll get to it as soon as time permits. Thank you!

**Comment by euskonadox** [comment]
Wow sorry @harrysolovay I've been very busy and I totally forgot to answer you, there is no problem right now. By the time if I need it I'll change it and submit a PR if you didn't.

Thank you :)

**Comment by harrysolovay** [comment]
@euskonadox no worries & thank you!

**Comment by fppgodinho** [comment]
was this ever resolved? i'm having this problem with the most recent versions of cli and use-stylelint-config...

**Comment by harrysolovay** [comment]
@fppgodinho never solved. Feel free to submit a PR though!

**Comment by samrith-s** [comment]
@harrysolovay Can you let me know where exactly I need to change it for this to work? I can raise a PR to fix this today.

**Comment by harrysolovay** [comment]
@samrith-s I don't recall where within the 3rd-party StyleLint packages... but [here is the initial package](https://github.com/harrysolovay/rescripts/blob/master/packages/rescripts/use-stylelint-config/index.js)––it worked for a short while, after which `stylelint-custom-processor-loader` (one of its dependencies) broke down :/

If you're able to create a Rescript that tends to this use case, **I'd be greatly appreciative!** Please let me know if you have other questions about the workings of Rescripts. I haven't used StyleLint in a while, so I probably won't be of much help in answering questions relating to its configuration. For any Rescripts plugin system questions, however, let me know :)
