### ISSUE TITLE
Continue compilation on tslint error with use-tslint-config

### ISSUE THREAD

**Issue by amakhrov** [harrysolovay/rescripts#26]
I was able to integrate CRA2 with tslint using rescripts-use-tslint-config.
However, my problem is that any error currently breaks the build instead of just being printed to the console. This behavior makes sense for CI pipeline, but is quite annoying during local development.

I'm wondering if it's possible to make this behavior configurable?

Thanks!

**Comment by harrysolovay** [comment]
If you go to [the source](https://github.com/harrysolovay/rescripts/blob/master/packages/rescripts/use-tslint-config/index.js), you'll see the options (including `failOnHint` and `emitErrors`) are hardcoded. Maybe this shouldn't be the case? For the time being, fork the repo & use whatever options you prefer. For a new version of this rescript, what options should I allow users to pass? (maybe the entire `tslint-loader` rule options?)
