### ISSUE TITLE
Export rescripted webpack config for 3rd party tools

### ISSUE THREAD

**Issue by bradbarrow** [harrysolovay/rescripts#27]
Hello, thanks for your work on this :)

I was wondering if there's a away to get the re-scripted configs output from `rescripts` as pure config for use in another tool?

`react-app-rewired` had this documented [here](https://github.com/timarney/react-app-rewired#4-provide-rewired-webpack-config-for-3rd-party-tools).

I'm looking for something similar :)

**Comment by harrysolovay** [comment]
Hi @bradbarrow –– the link didn't take me to the description, it took me to the top of the react-app-rewired page. Please do point me toward this, as I'm super interested in checking it out.

Currently, there is no rescript for that functionality. The difficulty is that the config is processed as an object, not as JavaScript plaintext. This sounds like more of a compiler plugin.

If you do think of a solution, please let me know. Maybe we can join forces & make something cool!

**Comment by bradbarrow** [comment]
Hey @harrysolovay sorry for the dodgy link.

Here you go https://github.com/timarney/react-app-rewired#4-paths-configuration---development--production

The key bit is this:

```
const { paths } = require('react-app-rewired');
// require normalized overrides
const overrides = require('react-app-rewired/config-overrides');
const config = require(paths.scriptVersion + '/config/webpack.config.dev');

module.exports = overrides.webpack(config, process.env.NODE_ENV);
```

I've tried something similar in rescripts and it's working ok but probably missing some edge cases:

```
.rescriptsrc

module.exports = [
  require.resolve('./config-overrides.js'),
];
```

```
overridenWebpackConfig.js

const { paths } = require('react-app-rewired');
const overrides = require('../config-overrides');

const config = require(paths.scriptVersion + '/config/webpack.config.js');
module.exports = overrides.webpack(config(process.env.NODE_ENV));
```

```
config-overrides.js

module.exports = {
  webpack: (config) => { ...adjustments ... }
}
```

**Comment by harrysolovay** [comment]
I think I see what you're saying: a way to take apply a given rescript to any config (non-CRA included)?

**Comment by izabelcalabria** [comment]
Hey, I just got notified this issue was closed, just wondering what is the solution? I was actually following this as I have a similar use case. I am using styleguidist on my project and in order for it to work with the webpack changes I need a way to provide it with webpack file containing the overrides.

**Comment by harrysolovay** [comment]
@izabelcalabria I unfortunately don't know of a good solution. Solving this problem involves manipulating the code itself... but a Rescripts config manipulates the resulting object (not the AST).
