### ISSUE TITLE
TypeError: normalizeLoaded(...) is not a function

### ISSUE THREAD

**Issue by frederikhors** [harrysolovay/rescripts#30]
I'm trying yo use rescripts (coming from react-app-rewired) all latest versions but I got this error:

`TypeError: normalizeLoaded(...) is not a function`

- package.json:
```json
...
  "devDependencies": {
    "@rescripts/cli": "0.0.10",
    "@rescripts/rescript-env": "0.0.5",
    "@rescripts/rescript-use-babel-config": "0.0.5"
...
}
```

- .rescriptsrc.js:
```js
module.exports = [['use-babel-config', '.babelrc']]
```

- .babelrc:
```
{
  "plugins": ["my-babel-plugin"]
}
```

Where am I wrong?

**Comment by harrysolovay** [comment]
Hi @frederikhors –– please try moving the config into your `package.json`

```json
...
  "rescripts": [["use-babel-config", ".babelrc"]]
...
```

**Comment by frederikhors** [comment]
Tried now.

The same behavior:

```
normalizeLoaded(creator)(...args)
                          ^
TypeError: normalizeLoaded(...) is not a function
```

**Comment by harrysolovay** [comment]
@frederikhors strange. Everything looks correct. Can you please send me a link to the repo, and I can check it out and debug?

**Comment by frederikhors** [comment]
Unfortunately it's a private project. Now I made it work again. Maybe an older `node_modules` folder but the problem still smell (maybe a problem with an older babel-plugin).

We can close this and if I find something maybe I can ping you for a reopen?

Also a question: why I need the line: `presets: ['react-app'],` in this file?:

- .babelrc.js:

```js
module.exports = {
  //presets: ['react-app'], // > Why I need this?
  plugins: ['graphql-tag']
}
```

If I remove this line it gives the error below:

```log
> rescripts build

Creating an optimized production build...
Failed to compile.

./src/index.js
SyntaxError: C:\project\src\index.js: Unexpected token (14:16)

  152 | }
  153 |
> 154 | ReactDOM.render(<Root />, document.getElementById('root'))
      |                 ^
  155 |
  156 | serviceWorker.register()
  157 |


npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

In original `create-react-app` or with `react-app-rewired` we don't need it, right?
(It is not a criticism. I love rescripts.)

**Comment by harrysolovay** [comment]
@frederikhors absolutely––reopen this if you run into any problems. As for why you need the `react-app` Babel preset: it includes transpilation instructions that allow you to use newer syntax (like ESModules), along with React-specific performance boosts, JSX support, cross-browser compatibility helpers, etc... definitely include that preset 👍

**Comment by frederikhors** [comment]
@harrysolovay, yes I know, but why I need to include it and with `create-react-app` or with `react-app-rewired` we don't need it?

It is already included somewhere else?

Can we include it also in rescripts?

**Comment by harrysolovay** [comment]
@frederikhors –– because Rescripts lets you configure babel directly. `create-react-app` locks you into using the `react-app` preset (you're wanting to override the config with a new one that uses the old config, in addition to a new plugin). As for `react-app-rewired`––it has a utility for adding plugins. This isn't the way [babel's documentation](https://babeljs.io) instructs users to configure the transpiler.

**Comment by zhaoyao91** [comment]
so rescripts is not overriding the old config, but replacing the old one with a new one?

**Comment by harrysolovay** [comment]
@zhaoyao91 it takes the old config, applies "rescripts" (functions which edit it and return a new config), and then, it injects the updated config into the require cache and requires react-scripts, which requires the cached (modified) config.

**Comment by jeroenkampinga** [comment]
I'm getting the same error as above. The code is placed in `.rescriptsrc.js`. Also tried moving the config to the `package.json` without any result. When removing `['use-babel-config', '.babelrc'],` it works just fine. 

I'm wondering how @frederikhors managed to resolve this issue.

**Comment by harrysolovay** [comment]
@jeroenkampinga to which error are you referring? The JSX parse error, or the "is not a function" error?

**Comment by jeroenkampinga** [comment]
> @jeroenkampinga to which error are you referring? The JSX parse error, or the "is not a function" error?

The "is not a function":

```
normalizeLoaded(creator)(...args)
                          ^
TypeError: normalizeLoaded(...) is not a function
```

**Comment by harrysolovay** [comment]
Can you please provide me a link to this code so I can take a look & debug?

**Comment by chattersley** [comment]
I installed ramda and @rescripts/utilities explicitly and it loaded. Looking at the internals was doing a couple of requires on those libs.

**Comment by harrysolovay** [comment]
@jeroenkampinga @chattersley –– is this resolved? If so, I'm hoping to close out this issue.

**Comment by jeroenkampinga** [comment]
@harrysolovay yes, sorry it's resolved. In my case it was a missing package which caused the error.

**Comment by passionkind** [comment]
@jeroenkampinga which package were you missing? I've got the same issue

**Comment by tbelch-at-eHealth-Tec** [comment]
@jeroenkampinga I also have the same issue!

**Comment by chattersley** [comment]
Try and install ramda and @rescripts/utilities explicitly @tbelch-at-eHealth-Tec . If this is added to the docs then I assume resolved.

**Comment by harrysolovay** [comment]
@jeroenkampinga @chattersley are `ramda` and `@rescripts/utilities` in fact the missing packages? Odd that `@rescripts/utilities` isn't being resolved by node (along with `ramda`, as a dependency of `@rescripts/utilities`). I'd very much like to help debug this, but I need to see a repro. If someone can provide me with this, I'll make sure to get the fix in / the fix documented.

**Comment by jeroenkampinga** [comment]
@harrysolovay I'm not sure if installing `ramda` was in fact the solution. I did try to install `radmda` among removing the `@rescripts/utilities` package.

**Comment by tbelch-at-eHealth-Tec** [comment]
@jeroenkampinga For me installing `ramda` solved this issues. I did not have to install `@rescripts/utilities`.
