### ISSUE TITLE
I don't understand how to translate this code from react-app-rewired to rescripts:

### ISSUE THREAD

**Issue by frederikhors** [harrysolovay/rescripts#32]
I don't understand how to translate this code from `react-app-rewired` to `rescripts`:

- config-overrides.js:

```js
const { injectBabelPlugin } = require('react-app-rewired')

module.exports = function override (config, env) {
  config = injectBabelPlugin('graphql-tag', config)
  return config
}
```

Maybe it's just me but I really don't understand this simply problem.

**How to?**

**Comment by harrysolovay** [comment]
@frederikhors you can use the `use-babel-config` Rescript to use your own Babel configuration:

`.babelrc`

```json
{
  "presets": [
    "react-app"
  ],
  "plugins": [
    "graphql-tag"
  ]
}
```
