### ISSUE TITLE
Add easy way to enable ESLint for TypeScript

### ISSUE THREAD

**Issue by cacay** [harrysolovay/rescripts#35]
There should be an option/package for enabling ESLint on `.ts` and `.tsx` files for those who do not want to use TSLint.

I managed to get this working with a custom config, but this should come pre-packaged. Here's the code (I would send a Pull Request but don't know where the best place to put this is):

```js
const isESLintLoader = node =>
  node && node.loader && node.loader.includes('eslint-loader');

const isESLintRule = node =>
  node && node.use && node.use.some(isESLintLoader);

const enableEslintForTypeScript = config => {
  const paths = getPaths(isESLintRule, config);
  const test = /\.(js|mjs|jsx|ts|tsx)$/;
  return edit(
    matchedSection => {
      return Object.assign({}, matchedSection, { test: test });
    },
    paths,
    config
  );
};
```

This should come with some documentation since ESLint doesn't work with TypeScript out of the box. The following is a good start:

```json
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "plugins": [
    "@typescript-eslint"
  ],
  "extends": "react-app"
}
```

You also need to install the packages used above:
```sh
npm install --save @typescript-eslint/parser @typescript-eslint/eslint-plugin
```

Finally, I'm not certain the code above covers everything. It matches what [`customize-cra. enableEslintTypescript()`](https://github.com/arackaf/customize-cra/blob/0c7e353243bc877d438415611dfe694807229de8/index.js#L122) does, and it's the only place in the Webpack config that refers to ESLint as far as I can tell. Additionally, `npm run build` does print lint messages. But `npm start` doesn't log lint messages to the console unlike [this](https://facebook.github.io/create-react-app/docs/getting-started#npm-start-or-yarn-start) claims.

**Comment by cacay** [comment]
Correction, `npm start` does print lint errors to the console, so the code is probably correct.

**Comment by harrysolovay** [comment]
@cacay thanks for reaching out about what you thought was a problem! Please let me know if you run into anything else that needs attention––& thanks for the PR 💯
