### ISSUE TITLE
No matching version found for @rescripts/rescript-use-babel-config@^0.0.7

### ISSUE THREAD

**Issue by rgnevashev** [harrysolovay/rescripts#36]
npm i and i get an error:
No matching version found for @rescripts/rescript-use-babel-config@^0.0.7
![2019-03-12 09:49:10](https://user-images.githubusercontent.com/123600/54180233-2528b800-44ac-11e9-9b61-33e055ec59ce.png)

**Comment by harrysolovay** [comment]
Hi @rgnevashev –– I'm really sorry about that! Just fixed it.

The other day, I pushed an update to the `use-babel-config` Rescript & it seems Lerna didn't update the dependency version in the `env` Rescript. Thanks for letting me know about this error.

Please let me know if you encounter any more problems :)
