### ISSUE TITLE
Add webpack plugins

### ISSUE THREAD

**Issue by codepunkt** [harrysolovay/rescripts#37]
To me, one of the main selling points of `react-app-rewired` is the ability to reconfigure webpack, for example by adding plugins in production mode.

How would i do this using `rescripts`?

**Comment by harrysolovay** [comment]
Hi @codepunkt –– you can absolutely do this with Rescripts. Check out [this section](https://github.com/harrysolovay/rescripts#rescript-sdk) of the docs; you'll likely want to use either the `appendWebpackPlugin` or `prependWebpackPlugin` helper. You can wrap your calls with `if (process.env.NODE_ENV) { ... }`.

Please let me know if you have any more questions.
