### ISSUE TITLE
Start script not working

### ISSUE THREAD

**Issue by shanetierney** [harrysolovay/rescripts#42]
The build script runs properly but the start scripts exits with status of 1 and there are no other errors. Below is the debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.7.0
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ld-ui@0.1.0\~prestart: ld-ui@0.1.0
6 info lifecycle ld-ui@0.1.0\~start: ld-ui@0.1.0
7 verbose lifecycle ld-ui@0.1.0\~start: unsafe-perm in lifecycle true
8 verbose lifecycle ld-ui@0.1.0\~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/T/Code/ld-ui/node_modules/.bin:/Users/T/.yarn/bin:/Users/T/.config/yarn/global/node_modules/.bin:/usr/local/opt/libpq/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/apr-util/bin:/usr/local/opt/openssl/bin:/usr/local/opt/apr/bin:/opt/local/bin:/opt/local/sbin:/Users/T/Library/Python/3.7/bin:/Users/T/Library/Python/2.7/bin:/Users/T/Library/Android/sdk//emulator:/Users/T/Library/Android/sdk//platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/:/opt/X11/bin
9 verbose lifecycle ld-ui@0.1.0\~start: CWD: /Users/T/Code/ld-ui
10 silly lifecycle ld-ui@0.1.0\~start: Args: [ '-c', 'rescripts start' ]
11 silly lifecycle ld-ui@0.1.0\~start: Returned: code: 1  signal: null
12 info lifecycle ld-ui@0.1.0\~start: Failed to exec start script
13 verbose stack Error: ld-ui@0.1.0 start: `rescripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid ld-ui@0.1.0
15 verbose cwd /Users/T/Code/ld-ui
16 verbose Darwin 18.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v8.10.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error ld-ui@0.1.0 start: `rescripts start`
22 error Exit status 1
23 error Failed at the ld-ui@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by shanetierney** [comment]
Found out that the issue was that I was using `removeWebpackPlugin` to remove plugins that didn't exist in the dev webpack config and it did not fail gracefully. Perhaps there should be a verbose error or fail silently if the plugin isn't found.

**Comment by harrysolovay** [comment]
@shanetierney –– thanks for the feedback. If you submit a PR, I'm more than happy to accept it! I don't currently have the bandwidth to work on error handling.
