### ISSUE TITLE
[Feature]: Add react-scripts config paths modifier

### ISSUE THREAD

**Issue by cncolder** [harrysolovay/rescripts#43]
I'm not sure if we can modify 'react-scripts/config/paths' exports before scripts running.

* Custom tsconfig: `require('react-scripts/config/paths').appTsConfig = path.resolve('tsconfig.dev.json')`
* Skip ForkTsCheckerWebpackPlugin: `require('react-scripts/config/paths').appTsConfig += '.not-exists'`

**Comment by harrysolovay** [comment]
Hi @cncolder — can you please further describe the issue. I’m a little hazy as to what you’re asking. Thank you!
