### ISSUE TITLE
CRA3 support?

### ISSUE THREAD

**Issue by Anahkiasen** [harrysolovay/rescripts#45]
Does this package currently support CRA3 already or does it require changes? I couldn't find a definitive answer in the README/issues so thought I'd ask

**Comment by harrysolovay** [comment]
@Anahkiasen haven't tried yet. If you give it a shot, will you please let me know the outcome?

**Comment by Anahkiasen** [comment]
Just did a test with my current project and things still compile fine but I'm doing minimal changes to the Webpack/Jest configurations, so it might be another story if you rescript a lot or use plugins etc. But looking promising so far :+1:

**Comment by harrysolovay** [comment]
@Anahkiasen great news!
