### ISSUE TITLE
Is there a way to use rescripts with tsc?

### ISSUE THREAD

**Issue by m93a** [harrysolovay/rescripts#46]
I've came to this package because [react-scripts-ts](https://www.npmjs.com/package/react-scripts-ts) became deprecated and I want custom `eslint` config and don't want to compile TypeScript with Babel. I've followed the steps described in README (installed rescripts, created .rescriptsrc, added use-eslint-config), but the build failed with
```
>yarn start
Failed to compile.

./src/registerServiceWorker.ts
  Line 12:  Parsing error: The keyword 'const' is reserved
```
Yes, I use `const` in my code. And I want to. How do I get the program to compile with `tsc` again?

**Comment by harrysolovay** [comment]
Hi @m93a –– CRA transpiles TypeScript via Babel... so Rescripts might not be a good fit for you (as it is a tool for patching CRA). As for the error you're getting, I need to know more about how you're setting up your project: are you using [the eslint rescript](https://github.com/harrysolovay/rescripts/tree/master/packages/rescripts/use-eslint-config) or [the tslint rescript](https://github.com/harrysolovay/rescripts/tree/master/packages/rescripts/use-tslint-config)? Either way, I believe this error stems from you not having the right linting configuration.

**Comment by m93a** [comment]
I'm sorry but I think I won't be able to elaborate on this further, because porting my application to a Babel-compatibile TypeScript would be too much of a struggle, so I'll just stick with the deprecated react-scripts-ts. We can leave this issue open for a bit if anyone cares and has the time to investigate it further. Or you can close it 🤷

Sorry to bother 🙂

**Comment by harrysolovay** [comment]
@m93a no worries––I should clarify one thing though: you wouldn't have to go through "porting [your] application to a Babel-compatible TypeScript"... this is the pre-configured TypeScript transpilation in CRA projects. All you would need is the `@rescripts/rescript-use-eslint-config`. Please let me know if you need further assistance.

Kind regards,

Harry

**Comment by Deveosys** [comment]
Hi @harrysolovay !
I would love some help configuring my project with rescripts to be able to transpile Typescript allowing namespaces.

Let's start from a fresh working CRA + electron + typescript project,
my setup would be  : 
- Create-React-App (--typescript)
- electron
- @rescripts/cli
- @rescripts/rescript-env

This is working well but i need to allow namespaces in Typescript.

**Comment by harrysolovay** [comment]
@Deveosys –– Namespaces are not available in the Babel TypeScript transform (which is what's being used in CRA). Check out [this thread](https://github.com/babel/babel/issues/8244)

**Comment by Deveosys** [comment]
@harrysolovay, what about the `allowNamespaces` option present in the doc ? 
https://babeljs.io/docs/en/babel-plugin-transform-typescript

**Comment by harrysolovay** [comment]
@Deveosys oh nice––they must've added that after the initial release. In that case, can you just use it via your Babel config? What problems are you running into?

**Comment by Deveosys** [comment]
@harrysolovay, thanks for your answers. The problem is that i'm not really confortable with webpack / babel and so rescripts config. 

So, from the setup i gave you, I'd have to add : 
```
module.exports = [
    [...],
    [
        'use-babel-config',
        {
            presets: ['react-app'],
            allowNamespaces: true
        }
    ]
];
      
```
to my `.rescripts.js`file ?

**Comment by harrysolovay** [comment]
Yep. That should do the trick.
