### ISSUE TITLE
Uninstallation - is it easy as I think it is?

### ISSUE THREAD

**Issue by YPCrumble** [harrysolovay/rescripts#47]
If I want to uninstall recripts, can I simply run `yarn remove rescripts` and then change the calls to `yarn start`, etc., in the package.json?

There isn't an explicit description of this in the documentation which I think would be very helpful. In my case, being able to uninstall this package without any hitches makes me much more likely to add it in the first place! 

If the procedure above is the case I'm happy to make a PR!

**Comment by harrysolovay** [comment]
Hi @YPCrumble –– I appreciate your concern, but I disagree with the idea that this is a problem: the documentation's job is NOT to describe usage of dependent technologies (namely NPM scripts & dependency management).

**Comment by YPCrumble** [comment]
@harrysolovay maybe I wasn't clear - sorry if that's the case. My question isn't related to dependent technologies (yarn, npm, etc.).

What I'm asking is whether rescripts is _reversible_ or not. It's not clear from the documentation whether this is something that I can add and later remove if the rescript I'm using is incorporated into create-react-app. Or is it closer to create-react-app's `eject` feature which locks me into an ejected (rescripted) app?

Am I able to add rescripts now and later remove it if I no longer need it? That's my question. I had thought that would be a nice feature to add to the documentation. The reason I like this project is it appears it doesn't lock me into something.

**Comment by harrysolovay** [comment]
That's correct: it does not lock you in. I believe this is already clear by nature of the swapped NPM scripts.

I want this tool to be easy to use... but it certainly isn't a beginner tool. And I don't want to over-explain in the documentation, as this detracts from other parts of the documentation. To make effective use of this tool, users need have basic knowledge of Node projects, and the underlaying build system of CRA.

**Comment by YPCrumble** [comment]
Thank you!
