### ISSUE TITLE
Create a build without it being modified or minified

### ISSUE THREAD

**Issue by diegodesouza** [harrysolovay/rescripts#51]
Is there a way to create a build without having it be modified or minified?

thanks

**Comment by harrysolovay** [comment]
Hi @diegodesouza sorry to only be responding now––this week has been hectic. There's absolutely a way: the solution lays in configuring Webpack though (it's not a Rescripts-specific solution). Your best bet is to check out [the react-scripts config](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js) (which exports the object that Rescripts patches). You can modify this config however suits your needs. Please let me know if you need anything else 👍
