### ISSUE TITLE
Use Different Sass Loader

### ISSUE THREAD

**Issue by brunoalano** [harrysolovay/rescripts#55]
Hello, thanks for mantaining this project. Actually I'm using CRA 3.x with Typescript, and it uses the `sass-loader` as default for Sass processing.

How could I change it to use the `yibn2008/fast-sass-loader`?

I found the issue #18, but I don't know if it applies to this too.

Best regards.

**Comment by brunoalano** [comment]
Fixed. But didn't get a way to make `~` imports (node_modules ref) to work.

**Comment by harrysolovay** [comment]
@brunoalano glad to hear you managed to fix it––have you tried `babel-plugin-module-resolver` ?
