### ISSUE TITLE
DefinePlugins always provides undefined to the app but works within rescripts.

### ISSUE THREAD

**Issue by sli** [harrysolovay/rescripts#56]
Title, basically.

I'm attempting to use the define plugin to pass a theme setting to the app so it can be built with either a dark or light theme, with the default being the light theme. This is how the DefinePlugin is setup (comments added to highlight the problem):

```js
module.exports = [
  ['use-babel-config', '.babelrc'],
  ['use-eslint-config', '.eslintrc'],
  addLessLoader,
  appendWebpackPlugin(new DefinePlugin({
    'process.env.THEME': JSON.stringify(THEME) // app always gets undefined
  })),
  // ... snipped, but it's split chunks, compression, and uglify -- production only
  configLogger
]
```

The logger looks like this, and as shown above, runs last:

```js
const configLogger = config => {
  console.dir(process.env.THEME)  // displays the correct value
  console.log('THEME IS:', THEME) // also displays the correct value
  return config
}
```

Console output:

```bash
Γ ****@**** Δ ~/****/ClientApp (ui/dark-theme)*
L Ω yarn build-dark
yarn run v1.16.0
$ set "NODE_ENV=production" && set "THEME=dark" && rescripts build
'dark'
THEME IS: dark
Creating an optimized production build...
```

So rescripts is definitely aware of the correct value.

I have also used this DefinePlugin config and got the same result:

```js
  appendWebpackPlugin(new DefinePlugin({
    'process.env': {
      THEME: JSON.stringify(THEME) // app always gets undefined
    }
  }))
```

And the result for this version is also the same, except accessing it causes the app to crash:

```js
  appendWebpackPlugin(new DefinePlugin({
    THEME: JSON.stringify(THEME) // app always gets undefined
  }))
```

While I would love to just use dotenv, this use-case is more of a customizable build setting and is not based on environment, so that's not going to cover my needs. I did try using dotenv to just provide the settings and pass them along, but the result was still the same.

Supplying the environment variable when running the build does make the `configLogger` function output the correct value, but still, it's undefined inside the app. When I build the app and run that version, it's also undefined there, so it's not a problem unique to just running it within the dev server, it also effects production builds.

**Comment by harrysolovay** [comment]
What is the `addLessLoader` Rescript? If `configLogger` has the middleware flag, it would log out the Webpack config, even if a later Rescript broke the pipeline.
