### ISSUE TITLE
Adding `.babelrc` by-passes Babel entirely

### ISSUE THREAD

**Issue by Domiii** [harrysolovay/rescripts#60]
## What I did:

1. `npm i -D @rescripts/cli @rescripts/rescript-env`
1. Update `package.json`'s `scripts` to use `rescripts` instead of `react-scripts`
1. Add `.rescriptsrc` (containing: `module.exports = [ "env"];`)
1. Add my own custom `.babelrc`

This is happening to me with `react-scripts@3.0.1`, as well as `react-scripts@2.1.8`.

A look at my `package.json` reveals:
```js
"devDependencies": {
    "@rescripts/cli": "0.0.10",
    "@rescripts/rescript-env": "0.0.10"
  }
```

## Expected:

Things to go as smoothly as they sometimes go in the occasional dream... ⭐⭐⭐⭐

## Currently:

It appears that Babel has been entirely bypassed; It does not recognize `jsx` anymore...

The contents of the `.babelrc` file do not matter at all. No matter if my own customized version, if empty or if you copy some basic templates from the web, the result is always the same: `babel` gets bypassed entirely, like so:

> Failed to compile.
> 
> ./src/index.js
> SyntaxError: /my-code/src/index.js: Unexpected token (18:16)
> 
>  16 | 
>  17 | 
>  18 | ReactDOM.render(&lt;Loading centered />, document.getElementById('root'));
>       |                                 ^

## The Twist
Things are working fine (except for legacy decorators, i.e. the CRA default babel config kicks in) if I remove my `.babelrc` file.

**Comment by Domiii** [comment]
Not sure what is causing it, but after getting rid of `rescripts` and ejecting, I still get the same problem - so probably not related to `rescripts`. Closing this. - Sorry for wasting your time!

**Comment by mariaines** [comment]
Hey @Domiii, I am having the same problem. Did you ever figure out a solution?

**Comment by harrysolovay** [comment]
@Domiii @mariaines that's because Rescripts doesn't merge with the pre-existing Babel config (the CRA preset). If you want this config (which includes the JSX transpilation), you'll need to specify the config manually:

`.babelrc`

```json
{
  "presets": [
    "react-app"
  ]
}
```

**Comment by mariaines** [comment]
Ah, great, thank you for the quick help @harrysolovay !
