### ISSUE TITLE
Configuring jest

### ISSUE THREAD

**Issue by scottnash** [harrysolovay/rescripts#61]
I need to update the moduleFileExtensions recognized by Jest, as indicated by the error below. I just can't figure out how to do that with Rescripts. I have my .rescriptsrc.js file and I'm able to adjust weback config and use a custom eslintrc file, but not seeing how to tweak Jest config.

```
Cannot find module './quotes' from 'index.js'

    However, Jest was able to find:
        './quotes.scss'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].
```

**Comment by harrysolovay** [comment]
Hi @scottnash I see that you closed the issue. Did you find a solution?

**Comment by jonathantneal** [comment]
I’ve added a config for this. See https://github.com/jsxtools/rescript-use-babel-jest-config

I’ve also made a PR to add it to the README: https://github.com/harrysolovay/rescripts/pull/64
