### ISSUE TITLE
append instead of replace config

### ISSUE THREAD

**Issue by aprilmintacpineda** [harrysolovay/rescripts#78]
What I did:

- install
- create .rescriptsrc

**.rescriptsrc**
```
module.exports = [
  ['use-babel-config', 'babel.config.js']
];
```

**babel.config.js**
```
module.exports = {};
```

rescripts seem to "replace" the actual configuration, however what I want to achieve is to "append" something to the configuration, I just want to add `babel-plugin-transform-remove-console`.

When I run `rescripts build`, it throws

Creating an optimized production build...
Failed to compile.

./src/index.js
SyntaxError:

```
  15 |
  16 | render(
> 17 |   <ApolloProvider client={client}>
     |   ^
  18 |     <ThemeProvider theme={theme}>
  19 |       <MuiPickersUtilsProvider utils={DateFnsUtils}>
  20 |         <SnackbarProvider
```

**Comment by harrysolovay** [comment]
Answered in #60 –– without the `react-app` Babel preset, you do not have JSX parsing. Try doing this instead:

`babel.config.json`

```js
module.exports = {
  presets: ["react-app"],
};
```

That should do the trick. Please let me know if you run into other errors. And please close this issue when ready.

**Comment by harrysolovay** [comment]
@aprilmintacpineda closing this out since I haven't heard back from you.
