### ISSUE TITLE
editWebpackPlugin changes not being applied

### ISSUE THREAD

**Issue by davidb1** [harrysolovay/rescripts#82]
I'm getting `Cannot read property 'filter' of undefined` when building a react project with multiple entry points, this comes from ManifestPlugin (**entrypoints.main.filter**). 

Overriding this in my `.rescriptsrc.js` does not prevent the error:
```
  config => {
    const edited = editWebpackPlugin(
      p => {
        p.generate = (seed, files, entrypoints) => {
          const manifestFiles = files.reduce((manifest, file) => {
            manifest[file.name] = file.path;
            return manifest;
          }, seed);
          // const entrypointFiles = entrypoints.main.filter(
          //   fileName => !fileName.endsWith('.map')
          // );

          return {
            files: manifestFiles,
            // entrypoints: entrypointFiles,
          };
        };
        return p;
      },
      "ManifestPlugin",
      config
    );
    return edited;
  }
```

But manually deleting these lines in the `webpack.config.js` makes the error go away

**Comment by harrysolovay** [comment]
@davidb1 it seems that the `editWebpackPlugin` filtration is failing. I'd recommend you `console.log` `p` and give it a run. If the following fails...

```js
config => {
  editWebpackPlugin(
    p => {
      console.log(p);
    },
    "ManifestPlugin",
    config
  );
  return config;
}
```

... then I'd recommend logging out your `config` and working your way down to the plugin that you want to modify. You can mutate `config` to achieve the behavior for which you're looking (even if it's not via the `editWebpackPlugin` util).
