### ISSUE TITLE
Remove plugin from `config.resolve`

### ISSUE THREAD

**Issue by garrettmaring** [harrysolovay/rescripts#84]
Webpack also provides support for plugins for the resolver.

`config.resolver.plugins = [ ... ]`

It would be a great feature if we had the same set of edit, append, delete, etc. features for those plugins.

**Comment by harrysolovay** [comment]
Couldn't you just append `plugins` to the config? Given that it's at the root level, the purpose of those utilities (to work even if their nested positions are changed by CRA maintainers) is void. Can you please give me an example of this?

**Comment by garrettmaring** [comment]
I want to remove the `ModuleScopePlugin`. Currently, I'm doing this:

```javascript
config.resolve.plugins = config.resolve.plugins.filter(plugin => !(plugin instanceof ModuleScopePlugin));
```

However, I was thinking it would be useful to do this with the either the `removeWebPlugin` helper recursively searching for the package, or with an option when calling it to look inside the resolver's plugins.

**Comment by harrysolovay** [comment]
I see what you're saying. Are there other instances where you'd want to identify and filter out anything of that instance type? How would you identify `config.plugins-filter`?

**Comment by harrysolovay** [comment]
@garrettmaring what's the word? Is it okay if I close out this issue?

**Comment by garrettmaring** [comment]
Sorry, for the delay here. After becoming more comfortable with edit/remove with getPaths, I think this isn't needed. It's easy to work with the current methods to accomplish the above 👍

**Comment by harrysolovay** [comment]
@garrettmaring glad to hear!
