### ISSUE TITLE
Setting a static name for the files generated by build

### ISSUE THREAD

**Issue by donfiftyidaho** [harrysolovay/rescripts#86]
I've got rescripts working for stopping the filenames being hashed and chunked, but I was wondering if there is a rescripts config to force the build to give me the same filename for each build?

I've seen [this issue](https://github.com/harrysolovay/rescripts/issues/51), but it's a bit ambiguous as to what wouldn't change. I'd like to avoid ejecting my app.

Right now I'm getting `main.<random number>.js`, it would be great to just get a `main.js` and `main.css` names generated.

My current `.rescriptsrc.js` file:

```module.exports = config => {
  config.optimization.runtimeChunk = false;
  config.optimization.splitChunks = {
    cacheGroups: {
      default: false
    }
  };
  return config;
};```

**Comment by donfiftyidaho** [comment]
I created a work around by reading the build/static/js dir and using a regex to get the file name.

Better to get a new version name each time anyway. 

Thanks for the rescripts package - works great

**Comment by harrysolovay** [comment]
Glad you think so :)
