### ISSUE TITLE
Webpack config

### ISSUE THREAD

**Issue by klaseca** [harrysolovay/rescripts#87]
I'm trying to add a alias to the webpack configuration, but I get an error when importing:  `Module not found: Can't resolve 'com/Common/Header/Header' in 'E:\dev\JavaScript\gqw\client\src'`.
`.webpack.config.js`:
```js
const { resolve } = require('path');

module.exports = config => {
  config.resolve.alias = Object.assign(config.resolve.alias, {
    app: resolve(__dirname, 'src/'),
    com: resolve(__dirname, 'src/components/'),
    store: resolve(__dirname, 'src/store/')
  });
  return config;
};
```
`.rescriptsrc.js`:
```js
module.exports = [require.resolve('./.webpack.config.js')];
```
What could be the problem?

**Comment by harrysolovay** [comment]
Does your webpack config file name start with a dot, or is that a typo? If it’s a typo, then the config isn’t being modified and the above error makes sense. I’ve never used that aliasing mechanism—if you’re certain there’s no typo and you’re making proper use of the API, I’ll attempt to repro and debug. Also, consider using babel-plugin-module-resolver instead. To me, it feels cleaner moving the responsibility of aliasing to the transpiler.

**Comment by klaseca** [comment]
Webpack config file name start with a dot. This method works in conjunction with the electron + react, but does not work in the react (maybe it is somehow connected). I will try to use babel-plugin-module-resolver.

**Comment by harrysolovay** [comment]
@klaseca how'd everything pan out?

**Comment by klaseca** [comment]
I just configured `jsconfig.json` file, for now this is enough for me.
