### ISSUE TITLE
[Question] Multiple entry points + shared/common chunks howto example for noobs

### ISSUE THREAD

**Issue by xenogenesi** [harrysolovay/rescripts#94]
I have a simple application created with CRA, now I need server side in case of certain errors to load a different html (which should still use some js / npm packages installed for the app), I would need to add entry points and maybe generate a shared / common chunk, I know that at the moment CRA does not support multiple entry points (there is an issue and an open PR but it is taking time), I would like to avoid using inject, I have seen rescripts mentioned in a response on Stackoverflow, it really is possible?

I looked at the documentation but if it is possible it is not clear to me how, I have no problems with node / npm / js but I am not very confident with webpack nor with CRA, it is my first project with these tools, until now I had used rollupjs and other frameworks, but for this project it is a requirement.

If it is possible, could someone point me to a working example?

Thank you

**Comment by harrysolovay** [comment]
There are several examples [here](https://github.com/harrysolovay/rescripts/tree/master/packages/examples). Your issue is very general and I'm not sure how I can help you, or if it relates to this library. Your question might get better reception on [StackOverflow](https://stackoverflow.com/).
