### ISSUE TITLE
Is there any way how to easily change paths?

### ISSUE THREAD

**Issue by etylsarin** [harrysolovay/rescripts#96]
Hi @harrysolovay , first,  thanks for this great tool, I really appreciate your work!

Is there a way, while using rescripts, how to rewire - let's say `appSrc` & `appIndexJs` from `react-scripts/config/paths.js`?

I tried to create rescripts file using following config with no luck:
```
module.exports = [
  {
    paths: config => ({
      ...config,
      appIndexJs: resolveModule(resolveApp, 'mySrc/index'),
      appSrc: resolveApp('mySrc')
    })
  }
]
```

**Comment by harrysolovay** [comment]
@etylsarin thank you the kind words! Unfortunately there is no first-class way of doing this as of right now... I don't believe `appIndexJs` nor `appSrc` exist at the top level of the webpack config. You'll need to dig around in [the CRA webpack config](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js) for the exact field(s) for which you're looking.

**Comment by etylsarin** [comment]
ok, I see. and from top of your head, would it be anyhow easy doable to involve react-app-rewired for this particular job? Seems this package offers it: https://github.com/timarney/react-app-rewired#4-paths-configuration---development--production

**Comment by harrysolovay** [comment]
It seems `paths` is a top-level option in that config... so very.
